### ISSUE TITLE
function not responding for smoothing 

### ISSUE THREAD

**Issue by PYmeas** [chstan/arpes#2]
i am having a hard time with the smoothing function i get the following error, i did import the arpres.analysis package :
`gaussian_filter_arr(data_mean, sigma={'phi':0.04}).S.plot()`

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-14-aab952d9ca1c> in <module>
     38 # data.S.fermi_surface.show()
     39 # spect.transpose('kp','eV').arpes.plotting.dispersion.cut_dispersion_plot()
---> 40 gaussian_filter_arr(data_mean, sigma={'phi':0.04}).S.plot()

NameError: name 'gaussian_filter_arr' is not defined
```

thank you for your help

**Comment by chstan** [comment]
Hi @PYmeas, from a quick search it looks like that function is actually defined in `arpes.analysis.filters`. I'll make a note to lift its export to `arpes.analysis` since I refer to it there in the docs.
